console.log("this is a practice shortcuts 1")
console.log("this is a practice shortcuts 2")
console.log("this is a practice shortcuts 3")
console.log("this is a practice shortcuts 4")
console.log("this is a practice shortcuts 5")
console.log("this is a practice shortcuts 6")
